services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: envvault-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - envvault
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: envvault-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: envvault
      MYSQL_USER: dipesh
      MYSQL_PASSWORD: dipesh
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - envvault
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: envvault-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - envvault
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: envvault-scheduler
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction & sleep 60; done"
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - envvault
    restart: unless-stopped

volumes:
  mysql-data:
  redis-data:

networks:
  envvault:
    driver: bridge
